"""initial_migration

Revision ID: 22881723f520
Revises: 
Create Date: 2023-01-09 00:20:50.909156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22881723f520'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('well_data',
    sa.Column('id', sa.String(), nullable=False, comment='Идентификатор данных скважины'),
    sa.Column('inclinometry', sa.String(), nullable=True, comment='Инклинометрия: измеренная по стволу глубина, м; вертикальная глубина, м'),
    sa.Column('d_cas', sa.Float(), nullable=True, comment='Данные по ЭК, м'),
    sa.Column('d_tub', sa.Float(), nullable=True, comment='Данные по НКТ, м'),
    sa.Column('h_tub', sa.Float(), nullable=True, comment='Глубина НКТ, м'),
    sa.Column('wct', sa.Float(), nullable=True, comment='Обводненность, %'),
    sa.Column('rp', sa.Float(), nullable=True, comment='Газовый фактор, м3/т'),
    sa.Column('gamma_oil', sa.Float(), nullable=True, comment='Отн. плотность нефти'),
    sa.Column('gamma_gas', sa.Float(), nullable=True, comment='Отн. плотность газа'),
    sa.Column('gamma_wat', sa.Float(), nullable=True, comment='Отн. плотность воды'),
    sa.Column('t_res', sa.Float(), nullable=True, comment='Пластовая температура, C'),
    sa.Column('p_wh', sa.Float(), nullable=True, comment='Буферное давление, атм'),
    sa.Column('geo_grad', sa.Float(), nullable=True, comment='Градиент температуры, C/100 м'),
    sa.Column('h_res', sa.Float(), nullable=True, comment='Глубина Верхних Дыр Перфорации, м'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vlp',
    sa.Column('id', sa.String(), nullable=False, comment='Идентификатор VLP'),
    sa.Column('vlp', sa.String(), nullable=True, comment='Дебиты жидкости, м3/сут, Забойное давление, атм'),
    sa.Column('well_id', sa.String(), nullable=True, comment='Идентификатор скважины'),
    sa.ForeignKeyConstraint(['well_id'], ['well_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vlp')
    op.drop_table('well_data')
    # ### end Alembic commands ###
